
HITO 3

#MERGE DE LAS DATAS

PASO 1: IMPORTAR LAS DOS DATAS
```{r}
library(rio)

#link base  1 Dana
libertad=import('https://github.com/DanaeNorah/Estadistica-para-el-Analisis-Politico-2-/raw/Trabajo/Libertad_civil.csv')
str(libertad)

#link base 2 Gabriela
sec=import('https://github.com/GabiCorazao/EstS2/raw/Trabajo/Acceso_Secundaria.csv')
str(sec)
```

PASO 2: MERGE
```{r}
baseLyS=merge(libertad,sec,by.x = "Country",by.y = "Country")
str(baseLyS)
```

PASO 3: MERGEAMOS CON LA TERCERA BASE DE GENDER

#Importamos base 3 Gender
```{r}
#link base 3 Winny
gender=import('https://github.com/Winny-calderon/Proyecto-EAP2/raw/master/GenderData.csv')
str(gender)
```
#Mergeamos nuestra baseLyS con Gender
```{r}
baseLSG=merge(baseLyS,gender,by.x = "Country",by.y = "Country")
str(baseLSG)
```
PASO 4: MERGE CON LA BASE 4 DE AUTONOMIA
#importamos la base de Mercy, de Autonomia, 
```{r}
#link base 4 Mercy
autonomia=import('https://github.com/mercy-diaz/ProyectoEst/raw/master/basefinal_MD.csv')
str(autonomia)
```

#merge para tener la base final
```{r}
basefinal=merge(baseLSG,autonomia,by.x = "Country",by.y = "Pais")
str(basefinal)
```

PASO 5: PREPARAMOS Y MODIFICAMOS NUESTRA BASE FINAL PARA HACERLA MÁS ENTENDEDIBLE
```{r}
#Uniformizar a 2 digitos el número de decimales a utilizar en nuestra data "basefinal" 
basefinal[,c(2:10)]=round(basefinal[,c(2:10)], digits = 2)

#cambiar nombres a las columnas
names(basefinal)[1]='Pais'
names(basefinal)[2]='VozPolitica'
names(basefinal)[3]='LibertadMov'
names(basefinal)[4]='AccesoJ'
names(basefinal)[5]='SecundariaC'
names(basefinal)[6]='Desempleo'
names(basefinal)[7]='CuentaF'
names(basefinal)[10]='DesigualdadGenero'

#ordenar las columnas para poner primero la variable dependiente
basefinal = basefinal [ , c(1,10,8,9,2,3,4,5,6,7)]
names (basefinal)

#Eliminamos los NAs
basefinal = na.omit(basefinal)

#Cambiando row.names
row.names(basefinal)=basefinal$Pais 

#verificamos
str(basefinal)
```
```{r}
#¿eliminar los paises o no?
basefinal=basefinal[,-c(1)]
```


