
Datas y limpieza:

```{r}
library(htmltab) #para scrapear
library(stringr) #para limpieza de columnas 
library(readr) #para extraer un único numero de la columna
library(rio) #para importar
library(cluster) #clustering
library(plyr) #aggregate, funcion each
library(psych) #para hacer tablas comparadas
library(knitr) #para generar tablas html
library(kableExtra) #para generar tablas html
library(factoextra) #visualización de clusters
library(ggrepel) #para que las etiquetas de los graficos no se superpongan
library(dplyr)
library(car) #recodificacion
library(magrittr)
library(foreign)
```

1. Urban data
```{r}
linkUrban="https://www.cia.gov/library/publications/resources/the-world-factbook/fields/349.html"
pathUrban='//*[@id="fieldListing"]'
urban=htmltab(linkUrban,pathUrban)
```
## Urban:

```{r}

PATRON="(\\-*\\d+\\.*\\d*)(?=\\%)"
COLSUCIA=urban$Urbanization

# UNA COLUMNA
urban$pop_urb=str_extract_all(string = COLSUCIA,
                              pattern= PATRON,
                              simplify = T)[,1]

# OTRA COLUMNA
urban$rate_urb=str_extract_all(string = COLSUCIA,
                               pattern=PATRON,
                               simplify = T)[,2]
urban$Urbanization=NULL

urban$Country=trimws(urban$Country,whitespace = "[\\h\\v]")

#numerica
str(urban)
urban[,c(2,3)]=lapply(urban[,c(2,3)], as.numeric)
str(urban)

# grabando
#write.csv(urban,"urban.csv", row.names = F)
```

2. Carbon data

```{r}
linkCO="https://www.cia.gov/library/publications/resources/the-world-factbook/fields/274.html"
pathCO='//*[@id="fieldListing"]'
co=htmltab(linkCO,pathCO)

```

## Carbon
```{r}
#mejores nombres
names(co)[2]='co'
co$co=str_split(string = co$co,
                pattern = '\\(',
                simplify = T)[,1]
co$unit=str_split(string = co$co,
                pattern = ' ',
                simplify = T)[,2]
co$co=str_split(string = co$co,
                pattern = ' ',
                simplify = T)[,1]
# table(co$unit)
co$co=gsub(",","",co$co)
co$unit=gsub("million",6,co$unit)
co$unit=gsub("billion",9,co$unit)
co$unit=gsub("Mt",0,co$unit)


# "en toda columna"
co[,]=lapply(co[,], trimws,whitespace = "[\\h\\v]")

#numerica
str(co)
co[,c(2,3)]=lapply(co[,c(2,3)], as.numeric)
str(co)

#write.csv(co,"co.csv", row.names = F)
```

3. Democracy data
```{r}
linkDemo="https://en.wikipedia.org/wiki/Democracy_Index"
pathDemo='//*[@id="mw-content-text"]/div[1]/table[2]'
demo=htmltab(linkDemo,pathDemo)
```
## LIMPIEZA DEMOCRACY

```{r}
# limpieza
names(demo)=str_split(names(demo),">>",simplify = T)[,1]%>%gsub('\\s','',.)
demo[,-c(1,8,9)]=lapply(demo[,-c(1,8,9)], trimws,whitespace = "[\\h\\v]") # no blanks
names(demo)=gsub("Â","",names(demo))
demo$Country=gsub("Â","",demo$Country)
demo$Country=trimws(demo$Country,whitespace = "[\\h\\v]") #PREGUNTAR CUAL ES LA DIFERENCIA ENTRE ESTE Y GSUB

# preparación
demo=demo[,-c(1)] #sin Rank
demo=demo[,-10]
demo[,-c(1,8,9)]=lapply(demo[,-c(1,8,9)], as.numeric) # a numerico
names(demo)[9]= 'Continent'


# veamos que tenemos:
str(demo)
```

###a. Los nombres de cada caso aparezcan en las gráficas:
```{r}
row.names(demo)=demo$Country
```

###b.Solo trabajemos con data sin valores perdidos:
```{r}
# alternativa a complete.cases:
demo=na.omit(demo)
```

4. GDP

```{r}
linkGDP="https://www.cia.gov/library/publications/resources/the-world-factbook/fields/211rank.html" 
pathGDP = '//*[@id="rankOrder"]'
gdp=htmltab(linkGDP,pathGDP)
```
## GDP

```{r}
library(readr)


names(gdp)=str_split(string = names(gdp),
                pattern = ' ',
                simplify = T)[,1]

gdp$GDP=parse_number(gdp$GDP)
gdp$Date=parse_number(gdp$Date)
names(gdp)[1]="rankGDP"
gdp[,]=lapply(gdp[,], trimws,whitespace = "[\\h\\v]")
#write.csv(gdp,"gdp.csv", row.names = F)
```

5. Freedom data
```{r}
linkFree="https://en.wikipedia.org/wiki/List_of_freedom_indices"
pathFree='//*[@id="mw-content-text"]/div[1]/table[2]'
free=htmltab(linkFree,pathFree)
```


```{r}
free=free[,-5] #eliminé dem index!

names(free)=c("Country","freeMundo","freeEco","freePress")

free$Country=gsub('Â','',free$Country)

free$freeEco=gsub("n/a",NA,free$freeEco)
free$freeMundo=gsub("n/a",NA,free$freeMundo)
free$freePress=gsub("n/a",NA,free$freePress)
free[,]=lapply(free[,], trimws,whitespace = "[\\h\\v]")

#write.csv(free,"free.csv", row.names = F)
```




