
SEMANA 8 - REPASO

#DATA 1 : MILITARY EXPEDITURES
```{r}
military = htmltab(doc = "https://www.cia.gov/library/publications/resources/the-world-factbook/fields/330rank.html", 
                which ='//*[@id="rankOrder"]')
```

```{r}
#cambiar datos
military$`Date of Information`=gsub(" est.","", military$`Date of Information`)

#volver a numericas
str(military)
military[,c(3,4)]=lapply(military[,c(3,4)], as.numeric)
str(military)

#eliminar Rank
military[1]=NULL

#sin espacios
military$Country=trimws(military$Country, whitespace = "[\\h\\v]")
```
PASO 2: SCRAPING
```{r}
url1= "https://www.cia.gov/library/publications/resources/the-world-factbook/fields/223.html" 

gini=htmltab(doc = url1, 
              which = '//*[@id="fieldListing"]',
              encoding = "UTF-8") 
head(gini)
```

limpieza
```{r}
names(gini)[2]='GI'
gini$GI1=str_split(string = gini$GI, pattern = '\\(', simplify = T)[,1]%>%parse_number()
str(gini)

```

MERGE
```{r}
base=merge(military,gini,by.x = "Country",by.y = "Country")
base[,c(3,4)]=NULL
```

```{r}
describeBy(base)
```

```{r}
plot(base$`(% of GDP)`, base$GI1)
```








NOTA:
```{r}
#datas[datas$`1985`=="..",`1985`]=NA #para solucionar esto tendría que cambiarle el nombre
#names(datas)[4]="a2018"
#datas[datas$a2018=="..",'a2018']=NA #listo ahora los hace NA

#datas$`2018`=gsub( '..',NA, datas$`2018``,fixed=T)#si coloco fixed no toma regex
#dos maneras de borrarlo
```

